---
title: "trd_log_csv_exploration"
author: "Andrea Pedot"
format: html
editor: visual
---

## Introduzione

I file principali utilizzati nello studio sono 4

-   il file excel "pt_names dati inclusione", che contiene una riga per paziente, con il successo o l'insuccesso del tentativo di svezzamento

-   il file excel "pt_registry dati giornalieri", che contiene una riga al giorno per paziente, che contiene i dati raccolti clinicamente oppure quelli da analisi di laboratorio (es. prelievo di sangue arterioso) e la storia clinica limitatamente a data di ricovero ospedaliero, in ICU, svezzamento, reintubazione, comparsa di complicanze e fine del ricovero

-   il file "TRD", aggegato in uno per paziente, che contiene una riga per minuto per paziente, contiene i dati registrati dal ventilatore, limitatamente allo stato del paziente

-   il file "LOG" aggegato in uno per paziente, che contiene una riga per minuto per paziente, contiene i dati registrati dal ventilatore, limitatamente ai segnali, gli allarmi e ai parametri che vengono impostati

Da questi dati è possibile ricostruire la storia di ogni tentativo di SBT o Trial di Respiro Spontaneo (potenzialmente anche molti per paziente, uno al giorno fino a quello di successo che porta allo svezzamento dal ventilatore).

L'ipotesi sperimentale che si vuole testare è se un modello sia in grado di offrire una performance soddisfacente nel predire l'esito del SBT dai dati raccolti nelle 24h che lo precedono.

## Pazienti inclusi

Dei 180 pazienti inclusi nello studio sono registrate le colonne che lo descrivono, in cui "id_univoco" contiene la chiave di associazione presente anche negli altri file.

Rilevanti come variabili che non cambiano durante il ricovero, potenzialmente utili per un'analisi successiva:

-   variabili demografiche come "sesso", "anni_eta", "kg_peso", "cm_altezza", "bmi" e "ibw"

-   le ragioni d'inizio della ventilazione meccanica in "name reason_mv"

-   date rilevanti come "data_ricovero ospedaliero", "data_ricovero_terapia intensiva", "data_inizio ventilazione meccanica", "data_fine ventilazione meccanica", "data_out_ti", "data_dimissione"

Mentre le altre colonne contengono variabili ridondanti, derivate oppure disponibili solo alla fine del ricovero del paziente.

```{r}
library(tidyverse)
library(readxl)
path_inclusione <- "C:/Users/andre/Unit of Biostatistics Epidemiology and Public Health/LEMBS - Weaning Study/Driving p e Weaning/pt_names dati inclusione.xlsx"

pt_names <- read_excel( path = path_inclusione,
                        sheet = "pt_names") |>
  select("id_pt",
         "id_univoco",
         "ospedale",
         "type",
         "sesso",
         "anni_eta",
         "kg_peso",
         "cm_altezza",
         "bmi", "ibw",
         "name reason_mv",
         starts_with("data"),
         starts_with("esito")) |> 
  select(-"data_reclutamento") |> 
  rename(reason = `name reason_mv` ,
         osp_in = `data_ricovero ospedaliero`,
         icu_in = `data_ricovero_terapia intensiva`,
         vm_inizio = `data_inizio ventilazione meccanica`,
         vm_fine = `data_fine ventilazione meccanica`,
         icu_out = data_out_ti,
         osp_out = data_dimissione,
         esito = `esito_osp 0 non impostato 1 dimesso 2 deceduto icu 3 deceduto osp`)
```

## Registro giornaliero dei pazienti

Tenendo a mente che in una giornata si svolge al più un SBT, l'obiettivo è quello di costruire per ogni paziente che rispetta i criteri della tabella 1 (che rispondono alla domanda "sospetto che il paziente possa essere pronto per un SBT?"), una riga che contenga tutti i dati delle 24 precedenti e il risultato.

Si noti come in questo caso la probabilità sia condizionata sulla risposta positiva alla valutazione clinica, visto che l'SBT non viene eseguito se non dietro decisione del medico.

Le variabili d'interesse sono:

-   "id_registry"

-   "id_univoco", che è chiave in comune con il file excel dei pz inclusi

-   "deleted", che permette di individuare le righe che contengono dati errati o incompleti

-   "data_lettura" identifica la data alla quale il tentativo si riferisce

-   le colonne che hanno come descrizione "weaning" e "SBT criteri di interruzione" contengono i parametri delle tabelle 1 (pre-SBT) e 2 (post-SBT). Si noti come
